language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - mkdir $HOME/bin
  - curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.6.tgz
  - tar -zxvf mongodb-linux-x86_64-3.0.6.tgz
  - mkdir -p $HOME/bin/mongodb
  - cp -R -n mongodb-linux-x86_64-3.0.6/* $HOME/bin/mongodb
  - export PATH=$HOME/bin/mongodb/bin:$PATH
  - mongod --version
  - java -version
  - npm install
  - npm install -g bower
  - bower install --production
script:
  - npm run -s build
  - bower install
  - npm run -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
